[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
# glib-sys = "0.9.1"
glib-sys = { git = "https://github.com/cthorner/sys", branch="crate-custom", version = "0.9.1" }
# gobject-sys = "0.9.1"
gobject-sys = { git = "https://github.com/cthorner/sys", branch="crate-custom", version = "0.9.1" }
libc = "0.2"

[dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"

[features]
v1_36_7 = []
v1_38 = ["v1_36_7"]
v1_42 = ["v1_38"]
dox = []

[lib]
name = "pango_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libpango-1.0"
homepage = "http://gtk-rs.org/"
keywords = ["pango", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "pango"
name = "pango-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.9.1"

[package.metadata.docs.rs]
features = ["dox"]
