[build-dependencies]
pkg-config = "0.3.7"

[dependencies]
gobject-sys = "0.9.1"
glib-sys = "0.9.1"
libc = "0.2"

[dev-dependencies]
shell-words = "0.1.0"
tempfile = "3"

[features]
v2_30 = []
v2_32 = ["v2_30"]
v2_34 = ["v2_32"]
dox = []

[lib]
name = "atk_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libatk-1"
homepage = "http://gtk-rs.org/"
keywords = ["atk", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "atk"
name = "atk-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.9.1"

[package.metadata.docs.rs]
features = ["dox"]
