[options]
work_mode = "sys"
library = "Gtk"
version = "4.0"
min_cfg_version = "3.94"
single_version_file = "."

external_libraries = [
   "GLib",
   "GObject",
   "Gio",
   "Atk",
   "GdkPixbuf",
   "Pango",
   "Cairo",
   "Graphene",
]

ignore = [
	"Gtk.BINARY_AGE",
	"Gtk.INTERFACE_AGE",
	"Gtk.MAJOR_VERSION",
	"Gtk.MICRO_VERSION",
	"Gtk.MINOR_VERSION",
]

[external_libraries]
gdk4 = "Gdk"
gsk4 = "Gsk"
