[options]
work_mode = "sys"
library = "Gsk"
version = "4.0"
min_cfg_version = "3.94"
single_version_file = "."

external_libraries = [
   "GLib",
   "GObject",
   "Pango",
   "Cairo",
   "Graphene",
]

[external_libraries]
gdk4 = "Gdk"
